.TH "src/log_helper.cpp" 3 "esp32c3_lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/log_helper.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'log_helper\&.h'\fP
.br
\fR#include 'mqtt_helper\&.h'\fP
.br
\fR#include <Arduino\&.h>\fP
.br
\fR#include <ArduinoJson\&.h>\fP
.br
\fR#include <settings\&.h>\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "String \fBgetLogLevelString\fP (\fBLogLevel\fP level)"
.br
.RI "ログレベルに応じた文字列を取得します。 "
.ti -1c
.RI "int \fBgetLogLevelInt\fP (\fBLogLevel\fP level)"
.br
.RI "ログレベルに応じた整数値を取得します。 "
.ti -1c
.RI "void \fBlogMessage\fP (\fBLogLevel\fP level, const String &message)"
.br
.RI "指定されたログレベルでメッセージを記録・出力します。 "
.in -1c
.SH "関数詳解"
.PP 
.SS "int getLogLevelInt (\fBLogLevel\fP level)"

.PP
ログレベルに応じた整数値を取得します。 LogLevel列挙型に対応する整数値を返します。

.PP
ログの優先度比較や、条件分岐の判定用に 指定された \fBLogLevel\fP 列挙型の値を対応する数値へ変換します。

.PP
\fB引数\fP
.RS 4
\fIlevel\fP 変換対象のログレベル（LogLevel型） 
.RE
.PP
\fB戻り値\fP
.RS 4
int 対応するログレベルの数値（未定義の場合は 0） 
.RE
.PP

.SS "String getLogLevelString (\fBLogLevel\fP level)"

.PP
ログレベルに応じた文字列を取得します。 LogLevel列挙型に対応する文字列を返します。

.PP
内部のデバッグログ出力時に、指定された \fBLogLevel\fP 列挙型の値を 対応する識別用の文字列（例: "ERROR", "WARN"）に変換するために使用します。

.PP
\fB引数\fP
.RS 4
\fIlevel\fP 変換対象のログレベル（LogLevel型） 
.RE
.PP
\fB戻り値\fP
.RS 4
String 対応するログレベルの文字列（未定義の場合は "UNKNOWN"） 
.RE
.PP

.SS "void logMessage (\fBLogLevel\fP level, const String & message)"

.PP
指定されたログレベルでメッセージを記録・出力します。 指定されたログレベルとメッセージを処理します。

.PP
現在の設定（CURRENT_LOG_LEVEL）と判定し、有効な場合にのみ処理を行います。 JSONバッファを生成してログデータを格納し、有効化されているマクロに応じて MQTT送信（LOG_TO_MQTT）やシリアル出力（LOG_TO_SERIAL）を行います。

.PP
\fB引数\fP
.RS 4
\fIlevel\fP ログメッセージの重要度（LogLevel型） 
.br
\fImessage\fP 記録するログ本文の文字列 
.RE
.PP

.SH "著者"
.PP 
 esp32c3_libのソースコードから抽出しました。
